//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> BookingDays { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<double> TotalCharges { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Extras { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual HotelInfo HotelInfo { get; set; }
        public virtual Room Room { get; set; }
    }
}
